### ISSUE TITLE
Inconsitent use of tabs and spaces in modules/excel4.py

### ISSUE THREAD

**Issue by PaperTsar** [mdsecactivebreach/SharpShooter#32]
Problem: modules/excel4.py mixes spaces and tabs.
Version: lastest master
Python version 3.9.0
OS: ParrotOS

Running `python3 SharpShooter.py ` results in:
```
Traceback (most recent call last):
  File "/mnt/hgfs/debian/SharpShooter/SharpShooter.py", line 21, in <module>
    from modules import *
  File "/mnt/hgfs/debian/SharpShooter/modules/excel4.py", line 39
    if i == 0:
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by ahmedx90T** [comment]
did found a solution for this issue  ?

**Comment by Loris1123** [comment]
You can edit the file `SharpShooter/modules/excel4.py` to remove the spaces and add tabs instead. It's only in a few lines. Not too much work.

There are already pull requests, where you can see the invalid lines: https://github.com/mdsecactivebreach/SharpShooter/pull/31/files

**Comment by AddaxSoft** [comment]
I fixed this too, should have checked this before @mdsec 
https://github.com/mdsecactivebreach/SharpShooter/pull/36

**Comment by saroyaj** [comment]
This fixed too: 

apt install python3-autopep8
autopep8 -i /opt/SharpShooter/modules/excel4.py

**Comment by sartlabs** [comment]
Thanks @jsinix, it worked like a charm! :)
