### ISSUE TITLE
initial_value must be unicode or None, not str

### ISSUE THREAD

**Issue by batutahibnu17** [mdsecactivebreach/SharpShooter#41]
Anyone facing this issue?

Command (e.g)
`python2.7 SharpShooter.py --payload js --dotnetver 4 --stageless --rawscfile shell.txt --output test`
```
Traceback (most recent call last):
  File "SharpShooter.py", line 599, in <module>
    ss.run(args)
  File "SharpShooter.py", line 527, in run
    payload_minified = jsmin(payload)
  File "/usr/local/lib/python2.7/dist-packages/jsmin/__init__.py", line 40, in jsmin
    ins = klass(js)
TypeError: initial_value must be unicode or None, not str
```

**Comment by wzw19890321** [comment]
> Anyone facing this issue?
> 
> Command (e.g) `python2.7 SharpShooter.py --payload js --dotnetver 4 --stageless --rawscfile shell.txt --output test`
> 
> ```
> Traceback (most recent call last):
>   File "SharpShooter.py", line 599, in <module>
>     ss.run(args)
>   File "SharpShooter.py", line 527, in run
>     payload_minified = jsmin(payload)
>   File "/usr/local/lib/python2.7/dist-packages/jsmin/__init__.py", line 40, in jsmin
>     ins = klass(js)
> TypeError: initial_value must be unicode or None, not str
> ```

Just stick with the original `jsmin` version `2.2.2` should fix this issue.
